meta:
  title: "Isaac Levien"
  description: "Composer, Bassist, Multidisciplinary Artist, Educator"
  facebook_image: "/img/res/1600/isaac-wall.jpg"
  twitter_image: "/img/res/1600/isaac-wall.jpg"
  image: "/img/res/1600/isaac-wall.jpg"
  twitter_handle: "@isaaclevien"
  domain: "isaaclevien.com"
  url: "http://isaaclevien.com"
  google_analytics_id: "UA-58345569-2"
  theme_color: "#FFFFFF"

name: ""
markdown: redcarpt
highlighter: pygments
permalink: "/:categories/:title/"

plugins:
  - jekyll-redirect-from

defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      footer: true

exclude:
  - node_modules
  - Gulpfile.js
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - redirects.json
  - README.md
  - LICENSE.md
